### ISSUE TITLE
pty-req interactive shell support

### ISSUE THREAD

**Issue by shazow** [gliderlabs/sshfront#2]
Need to be able to set bash as a handler and get an interactive shell when ssh'ing with no command.

**Comment by shazow** [comment]
@progrium What's the use case for the session channel? Is it for commands that require a pseudo-tty to function? Is there a specific example you have in mind?

**Comment by progrium** [comment]
Yes, and also just generally using execd as a frontend to a regular SSH server. I should be able to connect to execd with `ssh user@execdserver` and get an interactive shell with pty. This could be done by using a shell for the exec hook, or by connecting to another SSH server "backend".

Let me know if you need more requirements/example than that.

**Comment by shazow** [comment]
Not what you want, but passing in an empty string works as a shell. :P 

```
$ execd ... $(which true) $(which bash)
```

```
$ ssh ... localhost " "
echo hello world
hello world
pwd
/Users/shazow/local/go/src/github.com/progrium/execd
```

If we add "pty-req" to the "exec" case, it almost works too. `ssh -t` still fails due to incorrect cmdline parsing as it is and I suspect we'll need to session.RequestPty, session.Shell, then io-bind the pipes with the cmd's before it'll work completely. Will hammer away at it.

**(Some ninja-edits)**

**Comment by progrium** [comment]
Oh that's funny you can get it to work as is. But yeah, no pty. Anyway, sounds like you got it.
