### ISSUE TITLE
rename to sshfront?

### ISSUE THREAD

**Issue by progrium** [gliderlabs/sshfront#7]
I want to rename execd. This is a thread to discuss for a bit. As naming is subjective, it's easy to say "execd is fine" but I'd like add some requirements.
- make it clearly about ssh
- imply its uses as a programmable "frontend" (as in proxy/balancer/gateway, not ui)
- ideally easier to say and read than "execd"
- remain simple/short

As such, current best is "sshfront".

**Comment by cobyism** [comment]
"sshutthefrontdoor" :laughing:. Seriously though, what about something like "sshield"? Implies barrier layer in front of something else? "strap **sshield** onto whatever back-end **hand**lers you want"? Just thinking out aloud…

**Comment by cobyism** [comment]
… also just realised it ends with "d" for daemon. (I’m going to shut up now).

**Comment by progrium** [comment]
sshield is pretty good except i've given up on names that combine acronyms and words. the exception being when i just don't care about the name. but if i were into that, i'd be down for that one.

**Comment by cobyism** [comment]
> i've given up on names that combine acronyms and words

Yep, I definitely hear you. Carry on!
